### ISSUE TITLE
Missing version git tags

### ISSUE THREAD

**Issue by kloczek** [doug-gilbert/lsscsi#1]
Is it possible to add version tags?

**Comment by doug-gilbert** [comment]
4 tags added: r0.28, r0.29, r0.30 and r0.31 . Might be releasing 0.32 shortly and will update the tags here when I do. This repo is currently up to date by which I mean that it is in sync with my primary subversion repo.

**Comment by kloczek** [comment]
Thank you very much :)

Closing.
